version: '3.8'

services:
  db:
    container_name: 311-postgres
    image: gangstead/postgis:latest-arm
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - target: 5432
        published: ${DB_HOST_PORT}
    volumes:
      - backend_data:/var/lib/postgresql/data

  redis:
    container_name: 311-redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

  api:
    container_name: 311-api
    image: la311data/311_data_api:dev
    restart: ${API_RESTART_POLICY}
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      CACHE_ENDPOINT: redis
    ports:
      - target: ${APP_PORT}
        published: ${API_HOST_PORT}
    depends_on:
      - db
      - redis

  prefect:
    container_name: 311-prefect
    image: la311data/311_data_prefect:dev
    env_file: .env
    environment:
      PREFECT__CONTEXT__SECRETS__DSN: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}
      PREFECT__API_URL: ${APP_PROTOCOL}://${APP_HOST}:${APP_PORT}
    depends_on:
      - db

volumes:
  backend_data:
