name: Update Huggingface Dataset

on:
  schedule: # once daily at 10:45 pm PST (5:45 UTC)
    - cron: '45 5 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Setup environment
      run: |
        echo "HUGGINGFACE_LOGIN_TOKEN=${{ secrets.HUGGINGFACE_LOGIN_TOKEN }}" > .env

    - name: Run script
      run: python updateHfDataset.py
