name: Update Huggingface Dataset

on:
  schedule: # once daily at 10:30 pm PST (5 UTC)
    - cron: '30 5 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Change to scripts directory
      run: cd scripts/
      
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Setup environment
      run: |
        echo "HUGGINGFACE_LOGIN_TOKEN=${{ secrets.HUGGINGFACE_LOGIN_TOKEN }}" > .env
          
    - name: Run script
      run: python updateHfDataset.py
